import axios from '../utils/axiosWithExtra';


// GET_PROJECTS_LIST, GET_PROJECTS_LIST, GET_PROJECTS_LIST
export const GET_PROJECTS_LIST = "GET_PROJECTS_LIST"
export const GET_PROJECTS_LIST_SUCCESS = "GET_PROJECTS_LIST_SUCCESS"
export const GET_PROJECTS_LIST_FAILURE = "GET_PROJECTS_LIST_FAILURE"


// GET_PROJECT, GET_PROJECT_SUCCESS, GET_PROJECT_FAILURE
export const GET_PROJECT = "GET_PROJECT"
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS"
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE"


// ADD_PROJECT, ADD_PROJECT_SUCCESS, ADD_PROJECT_FAILURE
export const ADD_PROJECT = "ADD_PROJECT"
export const ADD_PROJECT_SUCCESS = "ADD_PROJECT_SUCCESS"
export const ADD_PROJECT_FAILURE = "ADD_PROJECT_FAILURE"


// UPDATE_PROJECT, UPDATE_PROJECT_SUCCESS, UPDATE_PROJECT_FAILURE
export const UPDATE_PROJECT = "UPDATE_PROJECT"
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS"
export const UPDATE_PROJECT_FAILURE = "UPDATE_PROJECT_FAILURE"


// DELETE_PROJECT, DELETE_PROJECT_SUCCESS, DELETE_PROJECT_FAILURE
export const DELETE_PROJECT = "DELETE_PROJECT"
export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS"
export const DELETE_PROJECT_FAILURE = "DELETE_PROJECT_FAILURE"